name: Build Nuitka Standalone Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka PyQt6 mcstatus requests psutil pyperclip ipaddress

      - name: Download UPX
        run: |
          Invoke-WebRequest -Uri https://github.com/upx/upx/releases/latest/download/upx-4.2.4-win64.zip -OutFile upx.zip
          Expand-Archive -Path upx.zip -DestinationPath ./upx
        shell: pwsh

      - name: Build executable with Nuitka
        run: |
          nuitka --standalone --onefile --python-flag=-O --upx-dir=./upx --include-package=PyQt6 \
          --include-package=mcstatus --include-package=requests --include-package=psutil --include-package=pyperclip \
          --include-package=ipaddress --include-package=re --windows-disable-console \
          --icon=./icons/favicon.ico CHNLFRP_UI.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CHNLFRP_UI-executable
          path: ./CHNLFRP_UI.dist/

      - name: Upload to cloud storage
        run: |
          import requests
          import json
          
          # Step 1: Login to get the token
          url = "http://chmlfrp_ui.frp.wtf/api/auth/login"#云盘地址
          payload = json.dumps({
              "username": "{{boring_student}}",
              "password": "{{12345678}}" #密码
          })
          headers = {'Content-Type': 'application/json'}
          response = requests.post(url, headers=headers, data=payload)
          token = response.json().get('token')

          # Step 2: Upload the file using the token
          upload_url = "http://chmlfrp_ui.frp.wtf/api/fs/form" #云盘地址
          file_path = "./CHNLFRP_UI.dist/CHNLFRP_UI.exe"  # Adjust if needed
          headers = {
              'Authorization': token,
              'Content-Length': str(len(open(file_path, 'rb').read())),
              'CHMLFRP_UI': 'desired/remote/path/CHNLFRP_UI.exe',  #File-Path=云盘文件地址
              'As-Task': 'true',
              'Content-Type': 'multipart/form-data'
          }
          with open(file_path, 'rb') as file:
              files = {'file': file}
              response = requests.put(upload_url, headers=headers, files=files)

          print(response.text)
