name: Build with Nuitka

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Nuitka
      run: |
        pip install nuitka

    - name: Build with Nuitka
      run: |
        nuitka --standalone --onefile --enable-plugin=pyqt6 --lto=full --output-dir=dist --icon=assets/favicon.ico CHMLFRP_UI.py

    - name: Upload the executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: CHMLFRP_UI
        path: dist/CHMLFRP_UI*
