name: Build with Nuitka

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Nuitka
      run: |
        pip install nuitka

    - name: Build with Nuitka
      run: |
        nuitka --standalone --onefile --follow-imports --enable-plugin=pyqt6 --lto=yes -o CHMLFRP_UI.exe --output-dir=build --windows-icon-from-ico=favicon.ico --windows-disable-console CHMLFRP_UI.py

    - name: Upload the executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: CHMLFRP_UI
        path: build/
